### ISSUE TITLE
调度who am i命令，日志不显示

### ISSUE THREAD

**Issue by hyperknob** [analysys/EasyScheduler#100]
在ui里创建一个最简单的shell 任务并放到dag中，内容为who am i，可以执行成功，但是查看任务实例的日志，并没有打印。显示没有日志。与此同时，escheduler的log server的日志会打印如下错误：
16:14:04.366 [grpc-default-executor-8] INFO cn.escheduler.server.rpc.LoggerServer - log parameter path : /app/escheduler-bin/logs/3/9/22.log ,skipLine : 0, limit : 10000
16:14:04.366 [grpc-default-executor-8] ERROR cn.escheduler.server.rpc.LoggerServer - read file failed : /app/escheduler-bin/logs/3/9/22.log
java.nio.file.NoSuchFileException: /app/escheduler-bin/logs/3/9/22.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.lines(Files.java:3744)
	at java.nio.file.Files.lines(Files.java:3785)
	at cn.escheduler.server.rpc.LoggerServer.readFile(LoggerServer.java:166)
	at cn.escheduler.server.rpc.LoggerServer.access$200(LoggerServer.java:38)
	at cn.escheduler.server.rpc.LoggerServer$LogViewServiceGrpcImpl.rollViewLog(LoggerServer.java:99)
	at cn.escheduler.rpc.LogViewServiceGrpc$MethodHandlers.invoke(LogViewServiceGrpc.java:418)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:650)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:14:04.366 [grpc-default-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0xaa5e2e06, L:/192.168.135.183:50051 - R:/192.168.135.183:52064] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 2] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
Apr 22, 2019 4:14:04 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@2a04a176
java.lang.NullPointerException
	at cn.escheduler.server.rpc.LoggerServer$LogViewServiceGrpcImpl.rollViewLog(LoggerServer.java:101)
	at cn.escheduler.rpc.LogViewServiceGrpc$MethodHandlers.invoke(LogViewServiceGrpc.java:418)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:650)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

目前测出只有who am i为如此，其他命令如ls和pwd之类的都没有问题

**Comment by hyperknob** [comment]
补充下，如果此命令换成whoami即无问题

**Comment by lidongdai** [comment]
Currently, there are restrictions on log display, and only a certain number of logs are displayed.

we will fix it in version 1.0.3
